// <auto-generated />
using System;
using KisuVerse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KisuVerse.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715113709_ExpandPerson")]
    partial class ExpandPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KisuVerse.Api.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action",
                            TmdbId = 28
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure",
                            TmdbId = 12
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation",
                            TmdbId = 16
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy",
                            TmdbId = 35
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crime",
                            TmdbId = 80
                        },
                        new
                        {
                            Id = 6,
                            Name = "Documentary",
                            TmdbId = 99
                        },
                        new
                        {
                            Id = 7,
                            Name = "Drama",
                            TmdbId = 18
                        },
                        new
                        {
                            Id = 8,
                            Name = "Family",
                            TmdbId = 10751
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantasy",
                            TmdbId = 14
                        },
                        new
                        {
                            Id = 10,
                            Name = "History",
                            TmdbId = 36
                        },
                        new
                        {
                            Id = 11,
                            Name = "Horror",
                            TmdbId = 27
                        },
                        new
                        {
                            Id = 12,
                            Name = "Music",
                            TmdbId = 10402
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mystery",
                            TmdbId = 9648
                        },
                        new
                        {
                            Id = 14,
                            Name = "Romance",
                            TmdbId = 10749
                        },
                        new
                        {
                            Id = 15,
                            Name = "Science Fiction",
                            TmdbId = 878
                        },
                        new
                        {
                            Id = 16,
                            Name = "TV Movie",
                            TmdbId = 10770
                        },
                        new
                        {
                            Id = 17,
                            Name = "Thriller",
                            TmdbId = 53
                        },
                        new
                        {
                            Id = 18,
                            Name = "War",
                            TmdbId = 10752
                        },
                        new
                        {
                            Id = 19,
                            Name = "Western",
                            TmdbId = 37
                        });
                });

            modelBuilder.Entity("KisuVerse.Api.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Awards")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("ProductionCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.MediaGenre", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("MediaId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaGenres");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.MediaPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .HasColumnType("text");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("PersonId");

                    b.ToTable("MediaPeople");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeathDay")
                        .HasColumnType("date");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("text");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.MediaGenre", b =>
                {
                    b.HasOne("KisuVerse.Api.Models.Genre", "Genre")
                        .WithMany("MediaGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KisuVerse.Api.Models.Media", "Media")
                        .WithMany("MediaGenres")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.MediaPerson", b =>
                {
                    b.HasOne("KisuVerse.Api.Models.Media", "Media")
                        .WithMany("MediaPeople")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KisuVerse.Api.Models.Person", "Person")
                        .WithMany("MediaPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.Genre", b =>
                {
                    b.Navigation("MediaGenres");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.Media", b =>
                {
                    b.Navigation("MediaGenres");

                    b.Navigation("MediaPeople");
                });

            modelBuilder.Entity("KisuVerse.Api.Models.Person", b =>
                {
                    b.Navigation("MediaPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
